# Generated by Django 5.1.7 on 2025-04-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="google_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
    ]
