# Generated by Django 3.2.25 on 2025-03-22 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('sol_balance', models.DecimalField(decimal_places=9, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='NFTHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mint_address', models.TextField()),
                ('nft_name', models.TextField()),
                ('image_url', models.TextField()),
                ('metadata_uri', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_address', models.TextField()),
                ('token_symbol', models.TextField()),
                ('amount', models.DecimalField(decimal_places=9, max_digits=30)),
                ('value_usd', models.DecimalField(decimal_places=2, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TokenPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_address', models.TextField()),
                ('price_usd', models.DecimalField(decimal_places=9, max_digits=20)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.TextField(unique=True)),
                ('block_time', models.DateTimeField()),
                ('tx_type', models.TextField()),
                ('token_address', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=9, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=9, max_digits=12)),
                ('status', models.TextField()),
                ('wallet_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.account', to_field='wallet_address')),
            ],
            options={
                'ordering': ['-block_time'],
            },
        ),
        migrations.AddIndex(
            model_name='tokenprice',
            index=models.Index(fields=['token_address'], name='api_tokenpr_token_a_a91fc1_idx'),
        ),
        migrations.AddField(
            model_name='tokenholding',
            name='wallet_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_holdings', to='api.account', to_field='wallet_address'),
        ),
        migrations.AddField(
            model_name='nftholding',
            name='wallet_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft_holdings', to='api.account', to_field='wallet_address'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet_address'], name='api_transac_wallet__5fa842_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['signature'], name='api_transac_signatu_c4d426_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenholding',
            index=models.Index(fields=['wallet_address'], name='api_tokenho_wallet__779ad1_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenholding',
            index=models.Index(fields=['token_address'], name='api_tokenho_token_a_bae16e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tokenholding',
            unique_together={('wallet_address', 'token_address')},
        ),
        migrations.AddIndex(
            model_name='nftholding',
            index=models.Index(fields=['wallet_address'], name='api_nfthold_wallet__8be4a0_idx'),
        ),
        migrations.AddIndex(
            model_name='nftholding',
            index=models.Index(fields=['mint_address'], name='api_nfthold_mint_ad_c7f274_idx'),
        ),
    ]
